Organizer.UI/Controllers/EventController.cs
using Organizer.BLL;
using Organizer.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organizer.UI.Controllers
{
    public class EventController : Controller
    {
        EventBLL eventBLL = new EventBLL();
        public ActionResult Index()
        {
            TempData["LeaveFrom"] = "Index";
            List<Events> eventList = eventBLL.ListEvents();
            return View(eventList);
        }

        [HttpGet]
        public ActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateEvent(Events filledEvent)
        {//TODO event oluşturunca otomatik olarak katılmış olsun.
            Users user = Session["User"] as Users;
            filledEvent.OwnerID = user.ID;
            filledEvent.NumberOfJoined = 0;
            eventBLL.InsertEvent(filledEvent);
            return RedirectToAction("MyEvents");
        }

        public ActionResult MyEvents()
        {
            Users user = Session["User"] as Users;
            List<Events> myEvents = eventBLL.GetMyEvents(user.ID);
            return View(myEvents);
        }

        [HttpGet]
        public ActionResult UpdateEvent(int id)
        {
            Events theEvent = eventBLL.GetEvent(id);
            return View(theEvent);
        }

        [HttpPost]
        public ActionResult UpdateEvent(Events updatedEvent)
        {
            Events eventInDB = eventBLL.GetEvent(updatedEvent.ID);
            eventInDB.Name = updatedEvent.Name;
            eventInDB.Picture = updatedEvent.Picture;
            eventInDB.EventDate = updatedEvent.EventDate;
            eventInDB.ApplicationDate = updatedEvent.ApplicationDate;
            eventInDB.Capacity = updatedEvent.Capacity;
            eventInDB.Description = updatedEvent.Description;
            eventBLL.UpdateEvent();
            return RedirectToAction("MyEvents");
        }

        public ActionResult DeleteEvent(int id)
        {//TODO IsDeleted kolonu ekleyip yap. bu haliyle zaten katılanlar ayrılmadan etkinliği silemiyor
            UserEvent userEvent = eventBLL.GetUserEvent(id);
            if (userEvent != null)
            {
                TempData["Delete"] = "Bütün kullanıcılar ayrılmadan etkinliği silemezsiniz!";
                return RedirectToAction("MyEvents");
            }
            eventBLL.DeleteEvent(id);
            return RedirectToAction("MyEvents");
        }

        public ActionResult JoinEvent(int id, int capacity, int numberOfJoined)
        {
            if (numberOfJoined < capacity) //TODO bu şartı kaldırabilirsin. iki tane parametreye de gerek kalmaz. zaten katıl linki görünmüyor şart sağlanmadıkça.
            {
                Events theEvent = eventBLL.GetEvent(id);
                theEvent.NumberOfJoined++;
                Users user = Session["User"] as Users;
                UserEvent userEvent = new UserEvent();
                userEvent.EventID = id;
                userEvent.UserID = user.ID;
                eventBLL.InsertUserEvent(userEvent);
            }
            return RedirectToAction("Index");
        }

        public ActionResult LeaveEvent(int id)
        {//TODO buraya numberOfJoined > 0 şartı konulabilir. ama zaten viewde Ayrıl linki görünmez oluyo, bu şarta gerek kalmıyo.
            Events theEvent = eventBLL.GetEvent(id);
            theEvent.NumberOfJoined--;
            UserEvent userEvent = eventBLL.GetUserEvent(id);
            eventBLL.DeleteUserEvent(userEvent);
            string leaveFrom = TempData["LeaveFrom"] as string;
            if (leaveFrom == "IJoined")
            {
                return RedirectToAction("IJoined");
            }

            return RedirectToAction("Index");
        }

        public ActionResult IJoined()
        {
            TempData["LeaveFrom"] = "IJoined";
            Users user = Session["User"] as Users;
            List<UserEvent> userEvent = eventBLL.GetIJoined(user.ID);
            return View(userEvent);
        }

        public ActionResult EventDetails(int id)
        {
            List<UserEvent> userEventList = eventBLL.ListUserEvents(id);
            return View(userEventList);
        }

        //public ActionResult MessageAll()
        //{

        //}

        //TODO etkinlik silindiğinde katılmış olan herkese mesaj gidecek
    }
}

Organizer.UI/Controllers/LoginController.cs
using Organizer.BLL;
using Organizer.Entity;
using Organizer.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organizer.UI.Controllers
{
    public class LoginController : Controller
    {
        LoginBLL loginBLL = new LoginBLL();
        public ActionResult Index()
        {
            return View();

        }

        public ActionResult Login(LoginModel model)
        {
            if (model.UserName == null || model.Password == null)
            {
                TempData["Error"] = "Email ya da şifre girmediniz!";
                return RedirectToAction("Index");
            }

            Users user = loginBLL.LoginUser(model.UserName, model.Password);

            //TempData["UserName"] = model.UserName.ToString();

            if (user == null)
            {
                TempData["Error"] = "Email ve şifre eşleşmedi!";
                return RedirectToAction("Index");
            }
            else
            {
                Session["User"] = user;
                return RedirectToAction("Index", "Event");
            }
        }

        public ActionResult Logout()
        {
            if (Session["User"] != null)
            {
                Session["User"] = null;
            }
            return RedirectToAction("Index");
        }

        //TODO silerken pop up çıkacak
        //TODO mesajlaşma yapılacak
    }
}

Organizer.UI/Controllers/MessageController.cs
using Organizer.BLL;
using Organizer.Entity;
using Organizer.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organizer.UI.Controllers
{
    public class MessageController : Controller
    {
        MessageBLL messageBLL = new MessageBLL();
        UserBLL userBLL = new UserBLL();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MyMessages()
        {
            Users user = Session["User"] as Users;
            List<Messages> messageList = messageBLL.GetMyMessages(user.ID);
            return View(messageList);
        }

        [HttpGet]
        public ActionResult SendMessage(int ownerID)
        {
            Messages message = new Messages();//eğer burda da SendBulkMessage ekşınlarındaki gibi kurgulasaydık o çokomelli yere gerek kalmayacaktı.
            message.ReceiverID = ownerID;
            Users user = userBLL.GetUser(ownerID);
            message.Users = user;
            return View(message);
        }

        [HttpPost]
        public ActionResult SendMessage(Messages message)
        {
            Users user = Session["User"] as Users;
            message.SenderID = user.ID;
            messageBLL.InsertMessage(message);
            return RedirectToAction("Index", "Event");
        }

        [HttpGet]
        public ActionResult SendBulkMessage()
        {
            #region Bu kısım sadece Alıcılar'ı view'de gösterebilmek için
            string receiverList = "";
            List<UserEvent> list = TempData["Bulk"] as List<UserEvent>;
            foreach (UserEvent item in list)
            {
                receiverList = receiverList + item.Users.Name + ", ";
            }
            ViewData["ReceiverList"] = receiverList.TrimEnd(',', ' ');
            #endregion

            return View();
        }
        
        [HttpPost]
        public ActionResult SendBulkMessage(Messages message)
        {
            List<UserEvent> list = TempData["Bulk"] as List<UserEvent>;
            Users user = Session["User"] as Users;
            foreach (UserEvent item in list)
            {
                message.ReceiverID = item.UserID;
                message.SenderID = user.ID;
                messageBLL.InsertMessage(message);
            }
            return RedirectToAction("MyMessages");
        }

        [HttpGet]
        public ActionResult ReplyMessage(int senderID)
        {
            Messages message = new Messages();
            message.ReceiverID = senderID;
            return View(message);
        }

        public ActionResult DeleteMessage(int id)
        {//TODO veritabanına IsDeleted kolonu ekleyip silinen mesajın IsDeleted değerini true ya da 1 yaparak hallet
            messageBLL.DeleteMessage(id);
            return RedirectToAction("MyMessages");
        }
        //public ActionResult MyMessages()
        //{

        //    //Messages message = messageBLL.GetMessage() ;
        //    Users user1 = userBLL.GetUser(message.SenderID);

        //    TempData["SenderName"] = user1.Name;
        //    Users user = Session["User"] as Users;
        //    List<Messages> messageList = messageBLL.MyMessages(user.ID);
        //    return View(messageList);

        //  //TODO burayı Message modeli oluşturup içine Messages tablosundan MessageText, Users tablosundan Name kısımlarını alarak yapmaya çalış
        //}

        //public ActionResult MyMessages2()
        //{

        //    //Messages message = messageBLL.GetMessage() ;
        //    //Users user1 = userBLL.GetUser(message.SenderID);

        //    //TempData["SenderName"] = user1.Name;
        //    Users user = Session["User"] as Users;
        //    List<Messages> messageList = messageBLL.MyMessages(user.ID);
        //    return View(messageList);

        //   //TODO burayı Message modeli oluşturup içine Messages tablosundan MessageText, Users tablosundan Name kısımlarını alarak yapmaya çalış
        //}

    }
}

Organizer.UI/Views/Shared/_Layout.cshtml
@using Organizer.Entity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Organizer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @{ 
        Users user = Session["User"] as Users;
    }
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["User"] != null)
                {
                    @Html.ActionLink("OlaylarOlaylar", "Index", "Event", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("OlaylarOlaylar", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @if (Session["User"] != null)
                    {
                        <li>@Html.ActionLink("🎪Tüm Etkinlikler", "Index", "Event")</li>
                        <li>@Html.ActionLink("📅Oluşturduklarım", "MyEvents", "Event")</li>
                        <li>@Html.ActionLink("🗓️Katıldıklarım", "Ijoined", "Event")</li>
                        <li>@Html.ActionLink("✉Mesajlarım", "MyMessages", "Message")</li>
                        <li>@Html.ActionLink("⚙" + user.Name,"UpdateUser","User")</li>//TODO Profil bilgileri güncelleme ve hesabı silme ekranı geldin tıklayınca
                        <li>@Html.ActionLink("🚪Çıkış", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Giriş Yap", "Index", "Login")</li>
                        <li>@Html.ActionLink("Kayıt Ol", "CreateUser", "User")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer class="navbar-fixed-bottom">
            <hr />
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>